name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  setup_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"

      - name: Current date
        run: |
          date

      - name: Directory Content
        run: |
          ls -l
