name: Deployment pipeline

on:
  push:
    branches: 
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
env:
  COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
  SKIP_CONDITION: ${{ contains(join(github.event.commits.*.message), '#skip') }}
  EVENT_NAME: ${{ github.event_name }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      
      - name: Install dependencies
        run: npm install

      - name: Check style
        run: npm run eslint

      - name: build
        run: npm run build

      - name: Jest test
        run: npm run test

      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Trigger deployment
        if: ${{ env.SKIP_CONDITION == 'false' && github.event_name == 'push' }}
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"

      - name: Successful deploy to server Discord notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() && env.SKIP_CONDITION == 'false' && github.event_name == 'push' }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "Pokedex Deployment Pipeline Success"
          description: "All tests passed. Commit depoyed to Render!"
          color: 0x008000
          url: "https://github.com/akskettu-hub/full-stack-open-pokedex/${{ github.sha }}"
          username: Pokedex Pipeline Bot
          
          

      - name: Failed deploy to server Discord notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "Pokedex Deployment Pipeline Failed!"
          description: "Commit `${{ github.sha }}` faild to pass tests or build!"
          color: 0xd42b12
          url: "https://github.com/akskettu-hub/full-stack-open-pokedex/${{ github.sha }}"
          username: Pokedex Pipeline Bot

  
  tag_release:
    if: ${{ !contains(join(github.event.commits.*.message), '#skip') && github.event_name == 'push' }}
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.73.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          PRERELEASE: true
          DRY_RUN: false
